# Site settings
title: Flowers and Machinery
email: marina.nattinger@gmail.com
description: Marina Nattinger's blog
baseurl: "/flowersandmachinery" # the subpath of your site, e.g. /blog/
url: "http://whatisamarina.github.io" # the base hostname & protocol for your site
twitter_username: whatisamarina
github_username:  whatisamarina

# Build settings
markdown: kramdown
